# Nome da sua automação (aparecerá na aba Actions)
name: Wake Up Streamlit App

# Define quando a automação deve ser executada
on:
  schedule:
    # Executa "às 0 minutos, a cada 4 horas, todos os dias"
    # Você pode ajustar este valor. Use https://crontab.guru/ para ajuda.
    - cron: '0 */4 * * *'
  workflow_dispatch:
    # Permite que você execute a automação manualmente a partir da aba Actions

# Define as tarefas que a automação irá executar
jobs:
  wakeup:
    runs-on: ubuntu-latest
    steps:
      - name: Envia um pedido para acordar o app
        # CORREÇÃO: Usa um comando mais robusto que simula um navegador
        run: curl -L -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" "https://socmarica.streamlit.app" > /dev/null
